### ISSUE TITLE
data rendering

### ISSUE THREAD

**Issue by mcohen113** [mcohen113/Project2#1]
can't figure out how to render data. Tried googling looked at a few different things nothing specific enough to my issue that I could understand.

Also, unsure where to start in reconfiguring my project to have a login and save that login to mongodb.

**Comment by mcohen113** [comment]
@gittheking
@jasonseminara
@trevorpreston
@rapala61
@irwintsay

**Comment by gittheking** [comment]
@mcohen113 can you please give more information regarding _which_ data you are having issues with rendering? Is it your API? Database data? Also, as per our parameters please include a snippet of code showing the method you are having an issue with, and also include the output (the faulty data or error that you're getting). 

As for the second part, we will be going over that shortly in  a mini lesson at 11am.

**Comment by mcohen113** [comment]
It's the API. I've tested by sticking some of it as a collection into a json file and importing that into mongo as a collection within my db.
Right now I can get my page to render, but can't understand how to pull data in - ie how to write function that does that.

![project2_holidays](https://cloud.githubusercontent.com/assets/22035945/19810144/4d12eafe-9cfa-11e6-8acd-63276ab344d5.png)
